<a href="https://colab.research.google.com/github/sabeehalam/Hamoye-Internship/blob/main/energy_efficiency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Mount the drive
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression,Ridge, Lasso
from sklearn.metrics import (mean_squared_error, mean_absolute_error, r2_score) 

In [65]:
df=pd.read_csv('energydata_complete.csv',engine='python')

In [66]:
df.head()

date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097

[5 rows x 29 columns]

In [67]:
df_1=df.drop(['date', 'lights'],axis=1)
df_1.head()

Appliances     T1       RH_1  ...  Tdewpoint        rv1        rv2
0          60  19.89  47.596667  ...        5.3  13.275433  13.275433
1          60  19.89  46.693333  ...        5.2  18.606195  18.606195
2          50  19.89  46.300000  ...        5.1  28.642668  28.642668
3          50  19.89  46.066667  ...        5.0  45.410389  45.410389
4          60  19.89  46.333333  ...        4.9  10.084097  10.084097

[5 rows x 27 columns]

In [68]:
X=df_1.drop('Appliances', axis=1)
y=df_1['Appliances']

In [69]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3, random_state=42)

In [70]:
minmax=MinMaxScaler()
minmax.fit_transform(X_train, y_train)
minmax.transform(X_test)

array([[0.43294615, 0.27554825, 0.12066877, ..., 0.3       , 0.51234794,
        0.51234794],
       [0.53854277, 0.85778509, 0.37727163, ..., 0.35454545, 0.46937859,
        0.46937859],
       [0.48574446, 0.27883772, 0.11146111, ..., 0.19090909, 0.00259746,
        0.00259746],
       ...,
       [0.43681802, 0.40712719, 0.18899927, ..., 0.51742424, 0.79266914,
        0.79266914],
       [0.55015839, 0.46732456, 0.33438333, ..., 0.52272727, 0.60824256,
        0.60824256],
       [0.43294615, 0.50219298, 0.21322995, ..., 0.74393939, 0.19877963,
        0.19877963]])

In [78]:
mlr=LinearRegression()
hist=mlr.fit(X_train, y_train)
y_pred=mlr.predict(X_test)

In [72]:
mean_squared_error(y_test, y_pred)

8768.535925051972

In [74]:
mse=mean_squared_error(y_pred, y_test)
mae=mean_absolute_error(y_pred, y_test)
r2=r2_score(y_pred, y_test)

In [77]:
rmse=pow(mse,0.5)
rmse

93.64046093998027

In [75]:
print(mse, mae, r2)

8768.535925051972 53.64297765584962 -4.411893747294925


In [79]:
hist.coef_

array([-3.70720673e-01,  1.63001980e+01, -1.83700295e+01, -1.37407481e+01,
        2.58367429e+01,  4.80316182e+00,  2.79366382e+00,  1.20498426e+00,
       -1.60084298e+00,  2.57510931e-01,  7.36354686e+00,  4.11648713e-01,
        1.04063061e+00, -1.69278695e+00,  9.99097025e+00, -5.77886090e+00,
       -2.11484524e+01, -1.76267959e+00, -1.10736285e+01,  1.70187889e-01,
       -1.09352104e+00,  2.23042487e+00,  2.02585717e-01,  5.70139259e+00,
        1.64829984e-02,  1.64829984e-02])

Quiz questions


In [55]:
X=df_1['T2'].to_numpy()
y=df_1['T6']
x=np.reshape(X,(-1,1))
x.shape
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

(19735, 1)

In [60]:
m1=LinearRegression()
hist=m1.fit(x,y)
y_pred=m1.predict(x)
mse=mean_squared_error(y_pred, y)
mae=mean_absolute_error(y_pred, y)
r2=r2_score(y_pred, y)

In [76]:
((y_test - y_pred) ** 2).sum() 

51918501.212232724

In [61]:
print(mse, mae, r2)

13.282121399544055 2.838473720687599 0.4421227162483343


In [62]:
((y - y_pred) ** 2).sum() 

262122.66582000192

In [64]:
pow(mse,0.5)

3.6444644873484573

In [84]:
rg=Ridge(alpha=0.4)
hist=rg.fit(X_train, y_train)
y_pred=rg.predict(X_test)
mse=mean_squared_error(y_pred, y_test)
pow(mse, 0.5)

93.64050398701556

In [87]:
rg=Lasso(alpha=0.001)
hist=rg.fit(X_train, y_train)
y_pred=rg.predict(X_test)
mse=mean_squared_error(y_pred, y_test)
pow(mse, 0.5)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6136226.8821879625, tolerance: 14642.917148544939
  positive)


93.64047772243323

In [88]:
hist.coef_

array([ -0.36651459,  16.29967497, -18.36317783, -13.73723101,
        25.83110181,   4.80204536,   2.788718  ,   1.20290031,
        -1.60161226,   0.25753728,   7.36032681,   0.41145013,
         1.03438863,  -1.69193633,   9.98826123,  -5.77897699,
       -21.13836072,  -1.7623376 , -11.05956632,   0.17020564,
        -1.0911855 ,   2.23056597,   0.202535  ,   5.6889568 ,
         0.03295809,   0.        ])