<a href="https://colab.research.google.com/github/sabeehalam/Hamoye-Internship/blob/main/Stability_of_the_Grid_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount the drive
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV 
from os import listdir

In [26]:
#reach the relevant
cd content/gdrive/MyDrive

SyntaxError: ignored

In [32]:
#Read the excel file to a pandas dataframe
df=pd.read_csv('Data_for_UCI_named.csv')

In [33]:
#output first five columns
df.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [34]:
#Drop stabf variable
df1=df.drop('stabf',axis=1)

In [35]:
#separate columns toindependent and dependent variables
X=df1.drop('stab',axis=1)
y=df1['stab']

In [36]:
#Split data into train and test sets
X_train, X_test, y_train, y_test=train_test_split( X, y, test_size=0.3, random_state=1)

In [37]:
#Scale the data
ss=StandardScaler()
ss.fit_transform(X_train,y_train)
ss.transform(X_test)

array([[ 0.59859735, -0.40851436,  1.50275117, ...,  1.16594247,
        -1.51947298,  1.08635556],
       [ 0.20783601,  0.37783975, -0.19031054, ..., -0.3974546 ,
         1.4084647 ,  1.22749488],
       [-1.07012833, -0.30962641, -0.88628304, ..., -1.44064567,
         0.64407968, -1.67768219],
       ...,
       [-1.57567885,  0.80027296,  0.42855906, ..., -0.92023029,
         1.69439709, -1.37250983],
       [-1.51643545, -0.2417414 , -0.67518489, ...,  0.22089891,
        -0.23411872,  0.78859853],
       [-0.87985064,  1.16260567, -0.56140345, ..., -1.24632636,
         1.5362551 , -1.48970973]])

In [44]:
#random forest implementation
rfr=RandomForestRegressor(random_state=1)
rfr.fit(X_train, y_train)
y_pred=rfr.predict(X_test)
mean_squared_error(y_test,y_pred)

0.00014509795143425504

In [45]:
#extra trees implementation
exr=ExtraTreesRegressor(random_state=1)
exr.fit(X_train, y_train)
y_pred=exr.predict(X_test)
mean_squared_error(y_test, y_pred)

0.000118892662181966

In [49]:
#XGB boosting implementation
xgbr=XGBRegressor(random_state=1)
xgbr.fit(X_train,y_train)
y_pred=xgbr.predict(X_test)
mean_squared_error(y_test, y_pred)

[06:23:31] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.00012639692106180823

In [50]:
#Lightgbm boosting implementation
lgbm=LGBMRegressor(random_state=1)
lgbm.fit(X_train,y_train)
y_pred=lgbm.predict(X_test)
mean_squared_error(y_test, y_pred)

7.398891688185189e-05

In [52]:
#extra trees improved by randomized search implementation
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
'min_samples_leaf': min_samples_leaf,
'min_samples_split': min_samples_split,
'max_features': max_features}

exr_imp=ExtraTreesRegressor(random_state=1)
rcv=RandomizedSearchCV(exr_imp, param_distributions=hyperparameter_grid)
hist=rcv.fit(X_train, y_train)
y_pred=rcv.predict(X_test)
mean_squared_error(y_test,y_pred)


0.00011682230074268336

In [53]:
#best parameters in the improved Extra Classifier
hist.best_params_

{'max_features': None,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 1000}

Classifier models


In [64]:
y=df['stabf']

In [65]:
#Split data into train and test sets
X_train, X_test, y_train, y_test=train_test_split( X, y, test_size=0.3, random_state=1)

In [67]:
dumm=pd.get_dummies(df['stabf'])
pd.concatdumm

stable  unstable
0          0         1
1          1         0
2          0         1
3          0         1
4          0         1
...      ...       ...
9995       0         1
9996       1         0
9997       1         0
9998       0         1
9999       0         1

[10000 rows x 2 columns]

In [68]:
#Scale the data
ss=StandardScaler()
ss.fit_transform(X_train)
ss.transform(X_test)

array([[ 0.59859735, -0.40851436,  1.50275117, ...,  1.16594247,
        -1.51947298,  1.08635556],
       [ 0.20783601,  0.37783975, -0.19031054, ..., -0.3974546 ,
         1.4084647 ,  1.22749488],
       [-1.07012833, -0.30962641, -0.88628304, ..., -1.44064567,
         0.64407968, -1.67768219],
       ...,
       [-1.57567885,  0.80027296,  0.42855906, ..., -0.92023029,
         1.69439709, -1.37250983],
       [-1.51643545, -0.2417414 , -0.67518489, ...,  0.22089891,
        -0.23411872,  0.78859853],
       [-0.87985064,  1.16260567, -0.56140345, ..., -1.24632636,
         1.5362551 , -1.48970973]])

In [69]:
#random forest implementation
rfr=RandomForestClassifier(random_state=1)
rfr.fit(X_train, y_train)
y_pred=rfr.predict(X_test)
accuracy_score(y_test,y_pred)

0.9173333333333333

In [89]:
#extra trees implementation
exr=ExtraTreesClassifier(random_state=1)
his=exr.fit(X_train, y_train)
y_pred=exr.predict(X_test)
accuracy_score(y_test, y_pred)

0.9206666666666666

In [90]:
his.feature_importances_

array([0.12056057, 0.11719745, 0.11066518, 0.11571542, 0.03959881,
       0.04085213, 0.04128182, 0.0408076 , 0.08871655, 0.0947766 ,
       0.09647193, 0.09335592])

In [71]:
#XGB boosting implementation
xgbr=XGBClassifier(random_state=1)
xgbr.fit(X_train,y_train)
y_pred=xgbr.predict(X_test)
accuracy_score(y_test, y_pred)

0.911

In [72]:
#Lightgbm boosting implementation
lgbm=LGBMClassifier(random_state=1)
lgbm.fit(X_train,y_train)
y_pred=lgbm.predict(X_test)
accuracy_score(y_test, y_pred)

0.935

In [73]:
#extra trees improved by randomized search implementation
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
'min_samples_leaf': min_samples_leaf,
'min_samples_split': min_samples_split,
'max_features': max_features}

exr_imp=ExtraTreesClassifier()
rcv=RandomizedSearchCV(exr_imp, param_distributions=hyperparameter_grid)
hist=rcv.fit(X_train, y_train)
y_pred=rcv.predict(X_test)
accuracy_score(y_test,y_pred)


0.9313333333333333

In [92]:
hist.best_estimator_.feature_importances_

array([0.141614  , 0.14056604, 0.13213324, 0.13445685, 0.00379731,
       0.00559665, 0.00550299, 0.00511901, 0.10145173, 0.10808637,
       0.11373768, 0.10793813])

In [74]:
#best parameters in the improved Extra Classifier
hist.best_params_

{'max_features': None,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 500}

In [83]:
#extra trees improved by randomized search implementation
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
'min_samples_leaf': min_samples_leaf,
'min_samples_split': min_samples_split,
'max_features': max_features}

exr_imp=ExtraTreesClassifier()
rcv=RandomizedSearchCV(exr_imp, param_distributions=hyperparameter_grid, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1, random_state = 1)
hist=rcv.fit(X_train, y_train)
y_pred=rcv.predict(X_test)
accuracy_score(y_test,y_pred)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.3min finished


0.9216666666666666

In [87]:
#best parameters in the improved Extra Classifier
hist.best_params_

{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [88]:
#extra trees improved by randomized search implementation
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
'min_samples_leaf': min_samples_leaf,
'min_samples_split': min_samples_split,
'max_features': max_features}

exr_imp=ExtraTreesClassifier(random_state=1)
rcv=RandomizedSearchCV(exr_imp, param_distributions=hyperparameter_grid, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1, random_state = 1)
hist=rcv.fit(X_train, y_train)
y_pred=rcv.predict(X_test)
accuracy_score(y_test,y_pred)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.3min finished


0.926